export const GET_COUNTRIES = 'GET_COUNTRIES';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const REGION_FILTER = 'REGION_FILTER';
export const SUBREGION_FILTER = 'SUBREGION_FILTER';
export const ORDER = 'ORDER';
export const APPLY_ORDER = 'APPLY_ORDER';
export const PAGINATE = 'PAGINATE';
export const RESET_FILTERS = 'RESET_FILTERS';